# fly.toml app configuration file generated for ana-lite-v1 on 2023-12-10T13:36:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ana-lite-v1"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
